package com.batterystaple.kmeasure

inline val yotta: Double get() = 10E24
inline val zetta: Double get() = 10E21
inline val exa: Double get() = 10E18
inline val peta: Double get() = 10E15
inline val tera: Double get() = 10E12
inline val giga: Double get() = 10E9
inline val mega: Double get() = 10E6
inline val kilo: Double get() = 10E3
inline val hecto: Double get() = 10E2
inline val deca: Double get() = 10E1
inline val deci: Double get() = 10E-1
inline val centi: Double get() = 10E-2
inline val milli: Double get() = 10E-3
inline val micro: Double get() = 10E-6
inline val nano: Double get() = 10E-9
inline val pico: Double get() = 10E-12
inline val femto: Double get() = 10E-15
inline val atto: Double get() = 10E-18
inline val zepto: Double get() = 10E-21
inline val yocto: Double get() = 10E-24

inline val Int.yotta: Double get() = this * com.batterystaple.kmeasure.yotta
inline val Int.zetta: Double get() = this * com.batterystaple.kmeasure.zetta
inline val Int.exa: Double get() = this * com.batterystaple.kmeasure.exa
inline val Int.peta: Double get() = this * com.batterystaple.kmeasure.peta
inline val Int.tera: Double get() = this * com.batterystaple.kmeasure.tera
inline val Int.giga: Double get() = this * com.batterystaple.kmeasure.giga
inline val Int.mega: Double get() = this * com.batterystaple.kmeasure.mega
inline val Int.kilo: Double get() = this * com.batterystaple.kmeasure.kilo
inline val Int.hecto: Double get() = this * com.batterystaple.kmeasure.hecto
inline val Int.deca: Double get() = this * com.batterystaple.kmeasure.deca
inline val Int.deci: Double get() = this * com.batterystaple.kmeasure.deci
inline val Int.centi: Double get() = this * com.batterystaple.kmeasure.centi
inline val Int.milli: Double get() = this * com.batterystaple.kmeasure.milli
inline val Int.micro: Double get() = this * com.batterystaple.kmeasure.micro
inline val Int.nano: Double get() = this * com.batterystaple.kmeasure.nano
inline val Int.pico: Double get() = this * com.batterystaple.kmeasure.pico
inline val Int.femto: Double get() = this * com.batterystaple.kmeasure.femto
inline val Int.atto: Double get() = this * com.batterystaple.kmeasure.atto
inline val Int.zepto: Double get() = this * com.batterystaple.kmeasure.zepto
inline val Int.yocto: Double get() = this * com.batterystaple.kmeasure.yocto

inline val Long.yotta: Double get() = this * com.batterystaple.kmeasure.yotta
inline val Long.zetta: Double get() = this * com.batterystaple.kmeasure.zetta
inline val Long.exa: Double get() = this * com.batterystaple.kmeasure.exa
inline val Long.peta: Double get() = this * com.batterystaple.kmeasure.peta
inline val Long.tera: Double get() = this * com.batterystaple.kmeasure.tera
inline val Long.giga: Double get() = this * com.batterystaple.kmeasure.giga
inline val Long.mega: Double get() = this * com.batterystaple.kmeasure.mega
inline val Long.kilo: Double get() = this * com.batterystaple.kmeasure.kilo
inline val Long.hecto: Double get() = this * com.batterystaple.kmeasure.hecto
inline val Long.deca: Double get() = this * com.batterystaple.kmeasure.deca
inline val Long.deci: Double get() = this * com.batterystaple.kmeasure.deci
inline val Long.centi: Double get() = this * com.batterystaple.kmeasure.centi
inline val Long.milli: Double get() = this * com.batterystaple.kmeasure.milli
inline val Long.micro: Double get() = this * com.batterystaple.kmeasure.micro
inline val Long.nano: Double get() = this * com.batterystaple.kmeasure.nano
inline val Long.pico: Double get() = this * com.batterystaple.kmeasure.pico
inline val Long.femto: Double get() = this * com.batterystaple.kmeasure.femto
inline val Long.atto: Double get() = this * com.batterystaple.kmeasure.atto
inline val Long.zepto: Double get() = this * com.batterystaple.kmeasure.zepto
inline val Long.yocto: Double get() = this * com.batterystaple.kmeasure.yocto

inline val Double.yotta: Double get() = this * com.batterystaple.kmeasure.yotta
inline val Double.zetta: Double get() = this * com.batterystaple.kmeasure.zetta
inline val Double.exa: Double get() = this * com.batterystaple.kmeasure.exa
inline val Double.peta: Double get() = this * com.batterystaple.kmeasure.peta
inline val Double.tera: Double get() = this * com.batterystaple.kmeasure.tera
inline val Double.giga: Double get() = this * com.batterystaple.kmeasure.giga
inline val Double.mega: Double get() = this * com.batterystaple.kmeasure.mega
inline val Double.kilo: Double get() = this * com.batterystaple.kmeasure.kilo
inline val Double.hecto: Double get() = this * com.batterystaple.kmeasure.hecto
inline val Double.deca: Double get() = this * com.batterystaple.kmeasure.deca
inline val Double.deci: Double get() = this * com.batterystaple.kmeasure.deci
inline val Double.centi: Double get() = this * com.batterystaple.kmeasure.centi
inline val Double.milli: Double get() = this * com.batterystaple.kmeasure.milli
inline val Double.micro: Double get() = this * com.batterystaple.kmeasure.micro
inline val Double.nano: Double get() = this * com.batterystaple.kmeasure.nano
inline val Double.pico: Double get() = this * com.batterystaple.kmeasure.pico
inline val Double.femto: Double get() = this * com.batterystaple.kmeasure.femto
inline val Double.atto: Double get() = this * com.batterystaple.kmeasure.atto
inline val Double.zepto: Double get() = this * com.batterystaple.kmeasure.zepto
inline val Double.yocto: Double get() = this * com.batterystaple.kmeasure.yocto