@file:Suppress("unused")
package com.batterystaple.kmeasure.dimensions

typealias ScalarDimension = Dimension<Mass0, Length0, Time0, Current0>
typealias TimeDimension = Dimension<Mass0, Length0, Time1, Current0>
typealias FrequencyDimension = Dimension<Mass0, Length0, TimeN1, Current0>
typealias LengthDimension = Dimension<Mass0, Length1, Time0, Current0>
typealias AreaDimension = Dimension<Mass0, Length2, Time0, Current0>
typealias VolumeDimension = Dimension<Mass0, Length3, Time0, Current0>
typealias DensityDimension = Dimension<Mass1, Length3, Time0, Current0>
typealias VelocityDimension = Dimension<Mass0, Length1, TimeN1, Current0>
typealias AccelerationDimension = Dimension<Mass0, Length1, TimeN2, Current0>
typealias MassDimension = Dimension<Mass1, Length0, Time0, Current0>
typealias MomentumDimension = Dimension<Mass1, Length1, TimeN1, Current0>
typealias ForceDimension = Dimension<Mass1, Length1, TimeN2, Current0>
typealias PressureDimension = Dimension<Mass1, LengthN1, TimeN2, Current0>
typealias EnergyDimension = Dimension<Mass1, Length2, TimeN2, Current0>
typealias PowerDimension = Dimension<Mass1, Length2, TimeN3, Current0>

typealias SquareTimeDimension = Dimension<Mass0, Length0, Time2, Current0>
typealias AbsmentDimension = Dimension<Mass0, Length1, Time1, Current0>
typealias AreaTimeDimension = Dimension<Mass0, Length2, Time1, Current0>
typealias MassTimeDimension = Dimension<Mass1, Length0, Time1, Current0>
typealias MassLengthDimension = Dimension<Mass1, Length1, Time0, Current0>
typealias ViscosityDimension = Dimension<Mass1, LengthN1, TimeN1, Current0>
typealias ActionDimension = Dimension<Mass1, Length2, TimeN1, Current0>
typealias InverseTimeSquaredDimension = Dimension<Mass0, Length0, TimeN2, Current0>
typealias MassFlowRateDimension = Dimension<Mass1, Length0, TimeN1, Current0>
typealias SpecificEnergyDimension = Dimension<Mass0, LengthN2, TimeN2, Current0>
typealias MassPerSquareTimeDimension = Dimension<Mass1, Length0, TimeN2, Current0>
typealias MassAreaDimension = Dimension<Mass1, Length2, Time0, Current0>
typealias SurfaceDensityDimension = Dimension<Mass1, LengthN2, Time0, Current0>
typealias IrradianceDimension = Dimension<Mass1, Length0, TimeN3, Current0>

typealias CurrentDimension = Dimension<Mass0, Length0, Time0, Current1>
typealias ChargeDimension = Dimension<Mass0, Length0, Time1, Current1>
typealias ElectricalPotentialDimension = Dimension<Mass1, Length2, TimeN3, CurrentN1>
typealias CapacitanceDimension = Dimension<MassN1, LengthN2, Time4, Current2>
typealias ResistanceDimension = Dimension<Mass1, Length2, TimeN3, CurrentN2>
typealias ConductanceDimension = Dimension<MassN1, LengthN2, Time3, Current2>
typealias MagneticFluxDimension = Dimension<Mass1, Length2, TimeN2, CurrentN1>
typealias MagneticFluxDensityDimension = Dimension<Mass1, Length0, TimeN2, CurrentN1>
typealias InductanceDimension = Dimension<Mass1, Length2, TimeN2, CurrentN2>
typealias CurrentDensityDimension = Dimension<Mass0, LengthN2, Time0, Current1>
typealias MagneticFieldStrengthDimension = Dimension<Mass0, LengthN1, Time0, Current1>
typealias ElectricFieldStrengthDimension = Dimension<Mass1, Length1, TimeN3, CurrentN1>
typealias ChargeDensityDimension = Dimension<Mass0, LengthN3, Time1, Current1>
typealias SurfaceChargeDensityDimension = Dimension<Mass0, LengthN2, Time1, Current1>
typealias PermittivityDimension = Dimension<MassN1, LengthN3, Time4, Current2>
typealias PermeabilityDimension = Dimension<Mass1, Length1, TimeN2, CurrentN2>

typealias InverseLengthDimension = Dimension<Mass0, LengthN1, Time0, Current0>
typealias InverseAreaDimension = Dimension<Mass0, LengthN2, Time0, Current0>
typealias InverseVelocityDimension = Dimension<Mass0, LengthN1, Time1, Current0>
typealias InverseAccelerationDimension = Dimension<Mass0, LengthN1, Time2, Current0>
typealias InverseMassDimension = Dimension<MassN1, Length0, Time0, Current0>
typealias InverseMomentumDimension = Dimension<MassN1, LengthN1, Time1, Current0>
typealias InverseForceDimension = Dimension<MassN1, LengthN1, Time2, Current0>
typealias InversePressureDimension = Dimension<MassN1, Length1, Time2, Current0>
typealias InverseEnergyDimension = Dimension<MassN1, LengthN2, Time2, Current0>
typealias TimeSquaredDimension = Dimension<Mass0, Length0, Time2, Current0>
typealias TimePerAreaDimension = Dimension<Mass0, LengthN2, Time1, Current0>
typealias InverseMassFlowRateDimension = Dimension<MassN1, Length0, Time1, Current0>

typealias DistanceDimension = LengthDimension
typealias SpeedDimension = VelocityDimension
typealias ImpulseDimension = MomentumDimension
typealias AngleDimension = ScalarDimension
typealias AngularVelocityDimension = FrequencyDimension
typealias AngularFrequencyDimension = FrequencyDimension
typealias AngularAccelerationDimension = InverseTimeSquaredDimension
typealias AngularMomentumDimension = ActionDimension
typealias WorkDimension = EnergyDimension
typealias HeatDimension = EnergyDimension
typealias RadiantFluxDimension = PowerDimension
typealias StressDimension = PressureDimension
typealias EnergyDensityDimension = PressureDimension
typealias MomentOfForceDimension = EnergyDimension
typealias SurfaceTensionDimension = MassPerSquareTimeDimension
typealias MassConcentrationDimension = DensityDimension
typealias WavenumberDimension = InverseLengthDimension
typealias VergenceDimension = InverseLengthDimension
typealias AreaPerTimeDimension = SpecificEnergyDimension
typealias VoltageDimension = ElectricalPotentialDimension
typealias ElectromotiveForceDimension = ElectricalPotentialDimension
typealias ImpedanceDimension = ResistanceDimension
typealias ReactanceDimension = ResistanceDimension
typealias HeatFluxDensityDimension = IrradianceDimension
typealias ElectricFluxDensityDimension = SurfaceChargeDensityDimension
typealias ElectricDisplacementDimension = SurfaceChargeDensityDimension
