@file:Suppress("unused")
package com.batterystaple.kmeasure.units

inline val quetta: Double get() = 1E30
inline val ronna: Double get() = 1E27
inline val yotta: Double get() = 1E24
inline val zetta: Double get() = 1E21
inline val exa: Double get() = 1E18
inline val peta: Double get() = 1E15
inline val tera: Double get() = 1E12
inline val giga: Double get() = 1E9
inline val mega: Double get() = 1E6
inline val kilo: Double get() = 1E3
inline val hecto: Double get() = 1E2
inline val deca: Double get() = 1E1
inline val deci: Double get() = 1E-1
inline val centi: Double get() = 1E-2
inline val milli: Double get() = 1E-3
inline val micro: Double get() = 1E-6
inline val nano: Double get() = 1E-9
inline val pico: Double get() = 1E-12
inline val femto: Double get() = 1E-15
inline val atto: Double get() = 1E-18
inline val zepto: Double get() = 1E-21
inline val yocto: Double get() = 1E-24
inline val ronto: Double get() = 1E-27
inline val quecto: Double get() = 1E-30

inline val Int.quetta: Double get() = this * com.batterystaple.kmeasure.units.quetta
inline val Int.ronna: Double get() = this * com.batterystaple.kmeasure.units.ronna
inline val Int.yotta: Double get() = this * com.batterystaple.kmeasure.units.yotta
inline val Int.zetta: Double get() = this * com.batterystaple.kmeasure.units.zetta
inline val Int.exa: Double get() = this * com.batterystaple.kmeasure.units.exa
inline val Int.peta: Double get() = this * com.batterystaple.kmeasure.units.peta
inline val Int.tera: Double get() = this * com.batterystaple.kmeasure.units.tera
inline val Int.giga: Double get() = this * com.batterystaple.kmeasure.units.giga
inline val Int.mega: Double get() = this * com.batterystaple.kmeasure.units.mega
inline val Int.kilo: Double get() = this * com.batterystaple.kmeasure.units.kilo
inline val Int.hecto: Double get() = this * com.batterystaple.kmeasure.units.hecto
inline val Int.deca: Double get() = this * com.batterystaple.kmeasure.units.deca
inline val Int.deci: Double get() = this * com.batterystaple.kmeasure.units.deci
inline val Int.centi: Double get() = this * com.batterystaple.kmeasure.units.centi
inline val Int.milli: Double get() = this * com.batterystaple.kmeasure.units.milli
inline val Int.micro: Double get() = this * com.batterystaple.kmeasure.units.micro
inline val Int.nano: Double get() = this * com.batterystaple.kmeasure.units.nano
inline val Int.pico: Double get() = this * com.batterystaple.kmeasure.units.pico
inline val Int.femto: Double get() = this * com.batterystaple.kmeasure.units.femto
inline val Int.atto: Double get() = this * com.batterystaple.kmeasure.units.atto
inline val Int.zepto: Double get() = this * com.batterystaple.kmeasure.units.zepto
inline val Int.yocto: Double get() = this * com.batterystaple.kmeasure.units.yocto
inline val Int.ronto: Double get() = this * com.batterystaple.kmeasure.units.ronto
inline val Int.quecto: Double get() = this * com.batterystaple.kmeasure.units.quecto

inline val Long.quetta: Double get() = this * com.batterystaple.kmeasure.units.quetta
inline val Long.ronna: Double get() = this * com.batterystaple.kmeasure.units.ronna
inline val Long.yotta: Double get() = this * com.batterystaple.kmeasure.units.yotta
inline val Long.zetta: Double get() = this * com.batterystaple.kmeasure.units.zetta
inline val Long.exa: Double get() = this * com.batterystaple.kmeasure.units.exa
inline val Long.peta: Double get() = this * com.batterystaple.kmeasure.units.peta
inline val Long.tera: Double get() = this * com.batterystaple.kmeasure.units.tera
inline val Long.giga: Double get() = this * com.batterystaple.kmeasure.units.giga
inline val Long.mega: Double get() = this * com.batterystaple.kmeasure.units.mega
inline val Long.kilo: Double get() = this * com.batterystaple.kmeasure.units.kilo
inline val Long.hecto: Double get() = this * com.batterystaple.kmeasure.units.hecto
inline val Long.deca: Double get() = this * com.batterystaple.kmeasure.units.deca
inline val Long.deci: Double get() = this * com.batterystaple.kmeasure.units.deci
inline val Long.centi: Double get() = this * com.batterystaple.kmeasure.units.centi
inline val Long.milli: Double get() = this * com.batterystaple.kmeasure.units.milli
inline val Long.micro: Double get() = this * com.batterystaple.kmeasure.units.micro
inline val Long.nano: Double get() = this * com.batterystaple.kmeasure.units.nano
inline val Long.pico: Double get() = this * com.batterystaple.kmeasure.units.pico
inline val Long.femto: Double get() = this * com.batterystaple.kmeasure.units.femto
inline val Long.atto: Double get() = this * com.batterystaple.kmeasure.units.atto
inline val Long.zepto: Double get() = this * com.batterystaple.kmeasure.units.zepto
inline val Long.yocto: Double get() = this * com.batterystaple.kmeasure.units.yocto
inline val Long.ronto: Double get() = this * com.batterystaple.kmeasure.units.ronto
inline val Long.quecto: Double get() = this * com.batterystaple.kmeasure.units.quecto


inline val Double.quetta: Double get() = this * com.batterystaple.kmeasure.units.quetta
inline val Double.ronna: Double get() = this * com.batterystaple.kmeasure.units.ronna
inline val Double.yotta: Double get() = this * com.batterystaple.kmeasure.units.yotta
inline val Double.zetta: Double get() = this * com.batterystaple.kmeasure.units.zetta
inline val Double.exa: Double get() = this * com.batterystaple.kmeasure.units.exa
inline val Double.peta: Double get() = this * com.batterystaple.kmeasure.units.peta
inline val Double.tera: Double get() = this * com.batterystaple.kmeasure.units.tera
inline val Double.giga: Double get() = this * com.batterystaple.kmeasure.units.giga
inline val Double.mega: Double get() = this * com.batterystaple.kmeasure.units.mega
inline val Double.kilo: Double get() = this * com.batterystaple.kmeasure.units.kilo
inline val Double.hecto: Double get() = this * com.batterystaple.kmeasure.units.hecto
inline val Double.deca: Double get() = this * com.batterystaple.kmeasure.units.deca
inline val Double.deci: Double get() = this * com.batterystaple.kmeasure.units.deci
inline val Double.centi: Double get() = this * com.batterystaple.kmeasure.units.centi
inline val Double.milli: Double get() = this * com.batterystaple.kmeasure.units.milli
inline val Double.micro: Double get() = this * com.batterystaple.kmeasure.units.micro
inline val Double.nano: Double get() = this * com.batterystaple.kmeasure.units.nano
inline val Double.pico: Double get() = this * com.batterystaple.kmeasure.units.pico
inline val Double.femto: Double get() = this * com.batterystaple.kmeasure.units.femto
inline val Double.atto: Double get() = this * com.batterystaple.kmeasure.units.atto
inline val Double.zepto: Double get() = this * com.batterystaple.kmeasure.units.zepto
inline val Double.yocto: Double get() = this * com.batterystaple.kmeasure.units.yocto
inline val Double.ronto: Double get() = this * com.batterystaple.kmeasure.units.ronto
inline val Double.quecto: Double get() = this * com.batterystaple.kmeasure.units.quecto